included:
 - MedMen
excluded:
disabled_rules:
  - cyclomatic_complexity
  - class_delegate_protocol
  - line_length
  - nesting
  - trailing_whitespace
  - identifier_name
  - multiple_closures_with_trailing_closure
  - colon
  - control_statement
  - for_where
  - function_body_length
  - file_length
  - type_body_length
opt_in_rules:
  - operator_usage_whitespace
  - force_unwrapping
force_try: warning
force_unwrapping: warning
force_cast: warning
type_name:
  max_length:
    warning: 50
    error: 60
