steps:
  - task: InstallAppleCertificate@2
    displayName: "Install an Apple certificate"
    inputs:
      certSecureFile: appstore_1130.p12
      certPwd: $(P12password)

  - task: InstallAppleProvisioningProfile@1
    displayName: "Install an Apple provisioning profile"
    inputs:
      provProfileSecureFile: appstore_com.medmen.Medmen.mobileprovision

  - script: |
      bin/buildVersion $(System.DefaultWorkingDirectory) $(Build.BuildId) $(majorVersion)
    displayName: "Update Version to latest"

  # - script: |
  #     curl -sL https://sentry.io/get-cli/ | bash
  #   displayName: "Update Sentry cli"

  - task: Cache@2
    displayName: Cache
    inputs:
      key: 'cacheV2 | pods | "$(Agent.OS)" | Podfile | Podfile.lock'
      path: 'Pods'
      cacheHitVar: 'PODS_CACHE_RESTORED'

  - task: CocoaPods@0
    displayName: "pod install"
    condition: ne(variables.PODS_CACHE_RESTORED, 'true')
    inputs:
      forceRepoUpdate: false

  - script: |
      bundle install
    displayName: Bundle Install

  - script: |
      bundle exec fastlane medmen_archive
    displayName: Archive IPA
    
  - task: CopyFiles@2
    displayName: "Copy Files"
    inputs:
      SourceFolder: $(System.DefaultWorkingDirectory)
      Contents: "build/MedMen.ipa"
      TargetFolder: $(Build.ArtifactStagingDirectory)

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact: MedMen"
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)
      ArtifactName: "MedMen"
